# GitHub Actions Workflow with MATLAB Actions
#
# For a general overview of GitHub Actions, see
# https://docs.github.com/en/actions
#
# For using MathWorks products in GitHub Actions, see
# https://github.com/matlab-actions/overview
#
# For details about the syntax of this file, see
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# Copyright 2021-2023 The MathWorks, Inc.

name: Create Jupyter notebooks from Live Scripts

on:
  workflow_dispatch:

jobs:

  job-generate-jupyter-files:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit jupyter 
      # notebooks to the repository
      contents: write

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: r2023b

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: R2023b
          products: |
            Simulink
            Simscape
            Simscape_Electrical
            Simscape_Driveline
            Powertrain_Blockset

      - name: Build Jupyter notebooks
        uses: matlab-actions/run-build@v1
        with:
          tasks: jupyter

      - name: Commit jupyter notebooks
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.ipynb'
